### ISSUE TITLE
Spammy error on plugin startup

### ISSUE THREAD

**Issue by BlazyDoesDev** [KovuTheHusky/dynmap-structures#42] opened 2021-04-08 18:03 UTC
**Describe the bug**
Spammy error on plugin startup

**To Reproduce**
1. Start a server running the plugin

**Expected behavior**

Plugin should start with no errors 

**Screenshots**
https://gist.github.com/BlazyDoesDev/ef8957c768c953f796e8f6c654238ca7

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS, Windows]
 - Java [e.g. 8, 11]: Java 11
 - Bukkit/Spigon: Paper version git-Paper-"3db3aaf39
 - dynmap: 3.1
 - dynmap-structures : Latest

**Additional context**
 Plugins (44): BannerMaker, Brewery, Chunky, ChunkyBorder, Citizens, CombatLogX, CoreProtect, CubCustomDrops, CustomCrafting, DisableWither*, DiscordSRV, dynmap*, Dynmap-Essentials*, Essentials, EssentialsGeoIP, EssentialsSpawn, ExecutableItems, FastAsyncWorldEdit (WorldEdit), floodgate-bukkit, Geyser-Spigot, Harbor, HeadDatabase, InvSeePlusPlus, lightEconomy, LiteBans, LockettePro, LuckPerms, Multiverse-Core, Orebfuscator, PlaceholderAPI, Plan, PlayerParticles, PlayerVaults, ProtocolLib, Sentinel, ServerlistMOTD*, SuperbVote, UltimateShops, Vault, VentureChat, Votifier, Wild, WolfyUtilities, WorldGuard

**Comment by KovuTheHusky** [comment] 2021-04-10 15:19
I believe this is a dupe of #37 and will be fixed once I release 2.3.1. I'll do my best to get to that today!

**Closed by KovuTheHusky** 2021-04-10 15:19 UTC
Labels: bug, duplicate

**Comment by KovuTheHusky** [comment] 2021-04-12 18:16
Please give [2.3.1](https://github.com/KovuTheHusky/dynmap-structures/releases/tag/2.3.1) a shot!
