### ISSUE TITLE
crashing server when loading chunks

### ISSUE THREAD

**Issue by PowerYuppie** [KovuTheHusky/dynmap-structures#19] opened 2019-06-23 08:30 UTC
I'm running a Spigot 1.14.2 server with Dynmap v3.0-beta-4.
Dynmap Structures loads just fine. But when I fly/walk around to discover more areas and therefore loading more chunks, the server crashes with a ConcurrentModificationException.

Others have contributed this to issues with plugins trying to read/modify the same list at the same time. Mostly because of calling the getChunk() method.

If I disable this plugin the server runs perfectly fine without any major issues.

Perhaps encapsulating the code in the code in the onChunkLoad event with a try/catch statement could be helpful.
Which is a good programming practice anyway.

Attaching my crash report.

[crash-2019-06-23_09.58.52-server.txt](https://github.com/KovuTheHusky/dynmap-structures/files/3317621/crash-2019-06-23_09.58.52-server.txt)

**Comment by KovuTheHusky** [comment] 2019-06-23 11:41
Duplicate of #17.

Also not solved by a try-catch as the exception is thrown from both accesses. Mine as well as the code in NMS.

**Closed by KovuTheHusky** 2019-06-23 11:41 UTC
Labels: bug
